- name: Build prometheus
  command: make -C ./build/prometheus
  delegate_to: localhost
- name: "Create user {{ prometheus_user }}"
  user:
    name: {{ prometheus_user }}
    comment: "Prometheus run user"
    append: true
    group: {{ prometheus_group }}
    shell: /bin/false
  become: true
- name: Install prometheus
  become: true
  copy:
    src: ./build/prometheus/prometheus
    dest: "{{ prometheus_path }}"
    mode: 0755
- name: Create prometheus folder paths
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: 0700
  with_items:
    - /etc/prometheus
    - "{{ prometheus_storage_path }}"
- name: Install prometheus configuration
  become: true
  template:
    src: prometheus.yml.tmpl
    dest: /etc/prometheus/config.yml
    mode: 0600
  notify: restart-prometheus
- name: Install prometheus systemd unit
  become: true
  template:
    src: prometheus.service.tmpl
    dest: /etc/systemd/system/prometheus.service
    mode: 0600
  notify: restart-prometheus
- name: Start prometheus
  become: true
  systemd:
    daemon_reload: yes
    name: prometheus
    state: started
    enabled: true

- import_tasks: node_exporter.yml
