- name: "Generate {{ locale }}"
  locale_gen:
    name: "{{ locale }}"
    state: present
- name: "Set {{ locale }}"
  become: true
  command: "update-locale LANG={{ locale }}"
- name: Set timezone to UTC
  timezone:
    name: Etc/UTC
- name: Create systemd-journald log path
  become: true
  file:
    path: /var/log/journal
    state: directory
    mode: 0600
  notify: restart-journald
- name: Update package index
  apt:
    update_cache: true
  become: true
- name: Install packages
  apt:
    package:
      - sudo
  become: true
- name: Check sudo group
  become: true
  group:
    name: sudo
    state: present
- name: "Allow passwordless sudo for {{ user_name }}"
  template:
    src: sudoers.tmpl
    dest: "/etc/sudoers.d/10-{{ user_name }}"
    mode: 0444
  become: true
- name: "Create user {{ user_name }}"
  become: true
  user:
    name: "{{ user_name }}"
    comment: "{{ user_email }}"
    append: true
    groups: sudo
    shell: /bin/bash
    password: "{{ user_password }}"
- name: Authorize SSH key
  authorized_key:
    user: "{{ user_name }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_kn_rsa.pub') }}"
  become: true
